name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}Plugin"
version: "${project.version}"
description: "${project.name} Purpur Plugin"
author: "BillyGalbreath"
api-version: "1.14"

commands:
  balance:
    description: View balance
    usage: /<command> (player)
    aliases:
      - bal
  economy:
    description: Manage economy
    usage: /<command>
    aliases:
      - eco
      - econ
  pay:
    description: Pay a player
    usage: /<command> [player]

permissions:
  command.balance:
    description: Allows viewing own balance
    default: true
  command.balance.others:
    description: Allows viewing other player balances
    default: true
  command.economy:
    description: Allows managing economy
    default: op
  command.pay:
    description: Allows paying other players
    default: true
